/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTradingModeRouteImport } from './routes/_authenticated/trading-mode'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRiskRouteImport } from './routes/_authenticated/risk'
import { Route as AuthenticatedMacroRouteImport } from './routes/_authenticated/macro'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated/diagnostics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChallengeRouteImport } from './routes/_authenticated/challenge'
import { Route as AuthenticatedBrokerConnectionsRouteImport } from './routes/_authenticated/broker-connections'
import { Route as AuthenticatedBacktestingRouteImport } from './routes/_authenticated/backtesting'
import { Route as AuthenticatedAutopilotRouteImport } from './routes/_authenticated/autopilot'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as ApiPublicWebhookTokenRouteImport } from './routes/api/public/webhook/$token'
import { Route as ApiPublicMarketXauusdRouteImport } from './routes/api/public/market/xauusd'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTradingModeRoute =
  AuthenticatedTradingModeRouteImport.update({
    id: '/trading-mode',
    path: '/trading-mode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiskRoute = AuthenticatedRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMacroRoute = AuthenticatedMacroRouteImport.update({
  id: '/macro',
  path: '/macro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallengeRoute = AuthenticatedChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrokerConnectionsRoute =
  AuthenticatedBrokerConnectionsRouteImport.update({
    id: '/broker-connections',
    path: '/broker-connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBacktestingRoute =
  AuthenticatedBacktestingRouteImport.update({
    id: '/backtesting',
    path: '/backtesting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutopilotRoute = AuthenticatedAutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhookTokenRoute = ApiPublicWebhookTokenRouteImport.update({
  id: '/api/public/webhook/$token',
  path: '/api/public/webhook/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketXauusdRoute = ApiPublicMarketXauusdRouteImport.update({
  id: '/api/public/market/xauusd',
  path: '/api/public/market/xauusd',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/autopilot': typeof AuthenticatedAutopilotRoute
  '/backtesting': typeof AuthenticatedBacktestingRoute
  '/broker-connections': typeof AuthenticatedBrokerConnectionsRoute
  '/challenge': typeof AuthenticatedChallengeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/macro': typeof AuthenticatedMacroRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trading-mode': typeof AuthenticatedTradingModeRoute
  '/api/public/market/xauusd': typeof ApiPublicMarketXauusdRoute
  '/api/public/webhook/$token': typeof ApiPublicWebhookTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/autopilot': typeof AuthenticatedAutopilotRoute
  '/backtesting': typeof AuthenticatedBacktestingRoute
  '/broker-connections': typeof AuthenticatedBrokerConnectionsRoute
  '/challenge': typeof AuthenticatedChallengeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/macro': typeof AuthenticatedMacroRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trading-mode': typeof AuthenticatedTradingModeRoute
  '/api/public/market/xauusd': typeof ApiPublicMarketXauusdRoute
  '/api/public/webhook/$token': typeof ApiPublicWebhookTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/autopilot': typeof AuthenticatedAutopilotRoute
  '/_authenticated/backtesting': typeof AuthenticatedBacktestingRoute
  '/_authenticated/broker-connections': typeof AuthenticatedBrokerConnectionsRoute
  '/_authenticated/challenge': typeof AuthenticatedChallengeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/macro': typeof AuthenticatedMacroRoute
  '/_authenticated/risk': typeof AuthenticatedRiskRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/trading-mode': typeof AuthenticatedTradingModeRoute
  '/api/public/market/xauusd': typeof ApiPublicMarketXauusdRoute
  '/api/public/webhook/$token': typeof ApiPublicWebhookTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/assistant'
    | '/autopilot'
    | '/backtesting'
    | '/broker-connections'
    | '/challenge'
    | '/dashboard'
    | '/diagnostics'
    | '/journal'
    | '/macro'
    | '/risk'
    | '/settings'
    | '/trading-mode'
    | '/api/public/market/xauusd'
    | '/api/public/webhook/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/assistant'
    | '/autopilot'
    | '/backtesting'
    | '/broker-connections'
    | '/challenge'
    | '/dashboard'
    | '/diagnostics'
    | '/journal'
    | '/macro'
    | '/risk'
    | '/settings'
    | '/trading-mode'
    | '/api/public/market/xauusd'
    | '/api/public/webhook/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/assistant'
    | '/_authenticated/autopilot'
    | '/_authenticated/backtesting'
    | '/_authenticated/broker-connections'
    | '/_authenticated/challenge'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostics'
    | '/_authenticated/journal'
    | '/_authenticated/macro'
    | '/_authenticated/risk'
    | '/_authenticated/settings'
    | '/_authenticated/trading-mode'
    | '/api/public/market/xauusd'
    | '/api/public/webhook/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicMarketXauusdRoute: typeof ApiPublicMarketXauusdRoute
  ApiPublicWebhookTokenRoute: typeof ApiPublicWebhookTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trading-mode': {
      id: '/_authenticated/trading-mode'
      path: '/trading-mode'
      fullPath: '/trading-mode'
      preLoaderRoute: typeof AuthenticatedTradingModeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risk': {
      id: '/_authenticated/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/macro': {
      id: '/_authenticated/macro'
      path: '/macro'
      fullPath: '/macro'
      preLoaderRoute: typeof AuthenticatedMacroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenge': {
      id: '/_authenticated/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof AuthenticatedChallengeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/broker-connections': {
      id: '/_authenticated/broker-connections'
      path: '/broker-connections'
      fullPath: '/broker-connections'
      preLoaderRoute: typeof AuthenticatedBrokerConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backtesting': {
      id: '/_authenticated/backtesting'
      path: '/backtesting'
      fullPath: '/backtesting'
      preLoaderRoute: typeof AuthenticatedBacktestingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autopilot': {
      id: '/_authenticated/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AuthenticatedAutopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhook/$token': {
      id: '/api/public/webhook/$token'
      path: '/api/public/webhook/$token'
      fullPath: '/api/public/webhook/$token'
      preLoaderRoute: typeof ApiPublicWebhookTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market/xauusd': {
      id: '/api/public/market/xauusd'
      path: '/api/public/market/xauusd'
      fullPath: '/api/public/market/xauusd'
      preLoaderRoute: typeof ApiPublicMarketXauusdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedAutopilotRoute: typeof AuthenticatedAutopilotRoute
  AuthenticatedBacktestingRoute: typeof AuthenticatedBacktestingRoute
  AuthenticatedBrokerConnectionsRoute: typeof AuthenticatedBrokerConnectionsRoute
  AuthenticatedChallengeRoute: typeof AuthenticatedChallengeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedMacroRoute: typeof AuthenticatedMacroRoute
  AuthenticatedRiskRoute: typeof AuthenticatedRiskRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTradingModeRoute: typeof AuthenticatedTradingModeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedAutopilotRoute: AuthenticatedAutopilotRoute,
  AuthenticatedBacktestingRoute: AuthenticatedBacktestingRoute,
  AuthenticatedBrokerConnectionsRoute: AuthenticatedBrokerConnectionsRoute,
  AuthenticatedChallengeRoute: AuthenticatedChallengeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedMacroRoute: AuthenticatedMacroRoute,
  AuthenticatedRiskRoute: AuthenticatedRiskRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTradingModeRoute: AuthenticatedTradingModeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicMarketXauusdRoute: ApiPublicMarketXauusdRoute,
  ApiPublicWebhookTokenRoute: ApiPublicWebhookTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
